'use strict';

export const ROLE_NAMES = {
  admin: 'admin',
  user: 'user',
};

export const DEFAULT_PAGINATION_SIZE = 10;

export const ENV_VAR_NAMES = {
  LIMITED_BONUSES_TIMEOUT_DAYS: 'LIMITED_BONUSES_TIMEOUT_DAYS',
  GETTING_PERCENT_BONUSES: 'GETTING_PERCENT_BONUSES',
  GIFT_BONUSES_USER_BIRTHDAY: 'GIFT_BONUSES_USER_BIRTHDAY',
  MAX_BONUSES_PER_PURCHASE_PERCENT: 'MAX_BONUSES_PER_PURCHASE_PERCENT',
};
